New RNG. Added user_fugacities command for use with multi-sorbate uvt systems.
1. The Rule 30 RNG algorithm was showing some strange correlations. Rather than investigate, I tore it out and replaced it with Mersenne Twister.
-> preset_seeds <int> <int> <int> <int>
this sets the random seed for the Mersenne Twister algorithm, but is OPTIONAL
if preset_seeds is not specified, the seeds will be read from /dev/urandom
the "seed <int>" command is now deprecated
 
2. Added "user_fugacities" command:
-> user_fugacities 0.5 1.2 3.2
sets fugacity for sorbate #1 (as specified in the insert.pdb) to 0.5 atm, etc.

3. fixed some standard error messages to call the error() -> prevents writing each message several times when running in parallel.

4. fixed unfreed memory and files associated with multi-sorbate runs

5. cleaned up some crap

diff --git a/build/configure b/build/configure
--- a/build/configure
+++ b/build/configure
@@ -62,13 +62,8 @@ case "$HOSTNAME" in
 	"circe") #USF research computing
 		case "$COMPILER" in
 			"gcc")
-
-				CC="gcc"
-				CFLAGS="-O3 -std=c99"
-				EXTRA_LIBS="-L./lib/ -lacml -lacml_mv -lacml_mp -lpgmp -lpgftnrtl -lrt -lm -rdynamic"
-				ln -s /usr/lib64/liblapack.so.3 ./lib/liblapack.a
-				ln -s /usr/lib64/libg2c.so.0 ./lib/libg2c.a
-				ln -s /usr/lib64/libblas.so.3 ./lib/libblas.a
+				echo "error: compiler $COMPILER not supported for machine $HOSTNAME"
+				exit 1
 			;;
 			"pgi")
 				CC="pgcc"
@@ -289,6 +284,11 @@ if [ $COMPILER = "gcc" ]; then
 else
 	GCC_EXTRA_LIBS=
 	EXTRA_LIBS=$EXTRA_LIBS
+fi
+
+## Some Mersenne Twister optimizations. Compiles fine without.
+if [ $COMPILER = "gcc" ]; then
+	MTFLAGS="-finline-functions -fomit-frame-pointer -fno-strict-aliasing --param max-inline-insns-single=1800 -std=c99"
 fi
 
 cat > Makefile << EOF
